=== openplanets/scape-toolwrapper/toolwrapper-data/src/main/resources/tool-1.0_draft.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://scape-project.eu/tool" elementFormDefault="qualified"
	xmlns="http://scape-project.eu/tool" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0">

	<xs:annotation>
		<xs:documentation>This schema ...</xs:documentation>
	</xs:annotation>

	<xs:element name="tool" type="Tool"/>

	<xs:complexType name="Tool">
		<xs:annotation>
			<xs:documentation>Describes a command line tool.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="installation" type="Installation" minOccurs="0"/>
			<xs:element name="otherProperties" type="Properties" minOccurs="0"/>
			<xs:element name="operations" type="Operations"/>
		</xs:sequence>
		<xs:attribute name="name" type="nonEmptyString" use="required"/>
		<xs:attribute name="version" type="nonEmptyString" use="required"/>
		<xs:attribute name="homepage" type="xs:anyURI"/>
		<xs:attribute name="schemaVersion" type="xs:decimal" use="required"/>
	</xs:complexType>


	<xs:complexType name="Installation">
		<xs:annotation>
			<xs:documentation>Declares 1 or more installation dependencies and
				license.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="dependency" type="OperatingSystemDependency" maxOccurs="unbounded"/>
			<xs:element name="license" type="License" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="License" mixed="true">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="LicenseType" use="required"/>
				<xs:attribute name="otherType" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="LicenseType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="GPLv1"/>
			<xs:enumeration value="GPLv2"/>
			<xs:enumeration value="GPLv3"/>
			<xs:enumeration value="LGPLv2.1"/>
			<xs:enumeration value="LGPLv3"/>
			<xs:enumeration value="BSD-old"/>
			<xs:enumeration value="BSD-new"/>
			<xs:enumeration value="FreeBSD"/>
			<xs:enumeration value="Apache Licence 2.0"/>
			<xs:enumeration value="Other"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="OperatingSystemDependency">
		<xs:annotation>
			<xs:documentation>Declares an operating system dependency.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="operatingSystemName" type="OperatingSystemName" use="required"/>
				<xs:attribute name="otherOperatingSystemName" type="xs:string"/>
				<xs:attribute name="operatingSystemVersion" type="xs:string"/>
				<xs:attribute name="format" type="DependencyFormat"/>
				<xs:attribute name="otherFormat" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="OperatingSystemName">
		<xs:annotation>
			<xs:documentation>The operating system name. Use "Other" together with
				@otherOperatingSystemName to specify a different operating
				system.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Debian"/>
			<xs:enumeration value="Ubuntu"/>
			<xs:enumeration value="Redhat"/>
			<xs:enumeration value="CentOS"/>
			<xs:enumeration value="Windows"/>
			<xs:enumeration value="MacOS"/>
			<xs:enumeration value="Other"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="DependencyFormat">
		<xs:annotation>
			<xs:documentation>The format of the dependency text must conform to one of the packaging
				systems. Use "Other" together with @otherFormat to specify a different packaging
				system.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Dpkg"/>
			<xs:enumeration value="RPM"/>
			<xs:enumeration value="Other"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="nonEmptyString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="InOut">
		<xs:sequence>
			<xs:element name="format" type="Format" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="InOutAttrs">
		<xs:complexContent>
			<xs:extension base="InOut">
				<xs:attribute name="name" type="xs:string" use="required"/>
				<xs:attribute name="required" type="xs:boolean"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Format" mixed="true">
		<xs:attribute name="registryName" type="xs:string" use="required"/>
		<xs:attribute name="version" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="Inputs">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element name="stdin" type="Stdin" maxOccurs="1" minOccurs="0"/>
			<xs:element name="input" type="Input" maxOccurs="unbounded" minOccurs="0"/>
			<xs:element name="parameter" type="Parameter" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Input">
		<xs:complexContent>
			<xs:extension base="InOutAttrs">
				<xs:sequence>
					<xs:element name="defaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="Parameter">
		<xs:complexContent>
			<xs:extension base="InOutAttrs">
				<xs:sequence>
					<xs:element name="defaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Stdin">
		<xs:complexContent>
			<xs:extension base="InOut">
				<xs:attribute name="required" type="xs:boolean"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Outputs">
		<xs:sequence>
			<xs:element name="stdout" type="Stdout" maxOccurs="1" minOccurs="0"/>
			<xs:element name="output" type="Output" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Output">
		<xs:complexContent>
			<xs:extension base="InOutAttrs">
				<xs:sequence>
					<xs:element name="extension" type="xs:string" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Stdout">
		<xs:complexContent>
			<xs:extension base="InOut"> </xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Operations">
		<xs:annotation>
			<xs:documentation>Declares 1 or more operations provided by the tool.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="operation" type="Operation" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Operation">
		<xs:sequence>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="command" type="xs:string"/>
			<xs:element name="inputs" type="Inputs"/>
			<xs:element name="outputs" type="Outputs"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="Properties">
		<xs:sequence>
			<xs:element name="property" type="Property" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Property" mixed="true">
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>

</xs:schema>

=== openplanets/scape-toolwrapper/README_FILES/digital-preservation-migration-image-imagemagick-image2jp2.xml
<?xml version="1.0" encoding="utf-8" ?>
<tool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://scape-project.eu/tool tool-1.0_draft.xsd" xmlns="http://scape-project.eu/tool" xmlns:xlink="http://www.w3.org/1999/xlink" schemaVersion="1.0" name="ImageMagick" version="1.0.0" homepage="http://www.imagemagick.org/script/convert.php">
  <installation>
    <dependency operatingSystemName="Debian">imagemagick</dependency>
    <license type="Apache Licence 2.0">Apache License, Version 2.0</license>
  </installation>
  <otherProperties>
    <property name="cost">0</property>
  </otherProperties>
  <operations>
    <operation name="digital-preservation-migration-image-imagemagick-image2jp2">
      <description>Converts any ImageMagick supported image format to JPEG2000</description>
      <command>/usr/bin/convert ${input} jp2:${output}</command>
      <inputs>
        <input name="input" required="true">
          <description>Reference to input file</description>
        </input>
        <parameter name="params" required="false">
          <description>Additional conversion parameters</description>
        </parameter>
      </inputs>
      <outputs>
        <output name="output" required="true">
          <description>Reference to output file</description>
          <extension>jp2</extension>
        </output>
      </outputs>
    </operation>
  </operations>
</tool>

=== openplanets/scape-toolwrapper/data/src/main/resources/pdfbox.xml
<?xml version="1.0" encoding="UTF-8"?>
<tool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://scape-project.eu/tool tool-1.0_draft.xsd"
	xmlns="http://scape-project.eu/tool" xmlns:xlink="http://www.w3.org/1999/xlink"
	name="PDFBox" version="0.10" homepage="http://pdfbox.apache.org/"
	schemaVersion="1.0">

	<installation>
		<dependency operatingSystemName="Debian">pdfbox-app-cli</dependency>
		<license type="Apache Licence 2.0">Apache License, Version 2.0</license>
	</installation>

	<otherProperties>
		<property name="cost">0</property>
		<property name="rating">5</property>
	</otherProperties>

	<operations>
		<operation name="pdf2txt">
			<description>Converts a PDF to a TXT (for more detailed info see: http://pdfbox.apache.org/commandlineutilities/ExtractText.html)</description>
			<command>pdfbox-app-cli ExtractText ${params} ${input} ${output}</command>
			<inputs>
				<input name="input" required="true">
					<description>Reference to input file</description>
				</input>
				<parameter name="params" required="false">
					<description>Additional conversion parameters</description>
				</parameter>
			</inputs>

			<outputs>
				<output name="output" required="true">
					<description>Reference to output file</description>
					<extension>txt</extension>
				</output>
			</outputs>
		</operation>

		<operation name="txt2pdf">
			<description>Converts a TXT to a PDF (for more detailed info see: http://pdfbox.apache.org/commandlineutilities/TextToPDF.html)</description>
			<command>pdfbox-app-cli TextToPDF ${params} ${output} ${input}</command>
			<inputs>
				<input name="input" required="true">
					<description>Reference to input file</description>
				</input>
				<parameter name="params" required="false">
					<description>Additional conversion parameters</description>
				</parameter>
			</inputs>

			<outputs>
				<output name="output" required="true">
					<description>Reference to output file</description>
					<extension>pdf</extension>
				</output>
			</outputs>
		</operation>
		<operation name="pdfs2pdf">
			<description>Merges a bunch of PDFs into a single PDF (for more detailed info see: http://pdfbox.apache.org/commandlineutilities/PDFMerger.html)</description>
			<command>pdfbox-app-cli PDFMerger ${input} ${output}</command>
			<inputs>
				<input name="input" required="true">
					<description>Reference to input file</description>
				</input>
				<parameter name="params" required="false">
					<description>Additional conversion parameters</description>
				</parameter>
			</inputs>

			<outputs>
				<output name="output" required="true">
					<description>Reference to output file</description>
					<extension>pdf</extension>
				</output>
			</outputs>
		</operation>
		<operation name="2pdfs2pdf">
			<description>Merges two PDFs into a single PDF (for more detailed info see: http://pdfbox.apache.org/commandlineutilities/PDFMerger.html)</description>
			<command>pdfbox-app-cli PDFMerger ${input1} ${input2} ${output}</command>
			<inputs>
				<input name="input1" required="true">
					<description>Reference to the first input file</description>
				</input>
				<input name="input2" required="true">
					<description>Reference to the second input file</description>
				</input>
				<parameter name="params" required="false">
					<description>Additional conversion parameters</description>
				</parameter>
			</inputs>

			<outputs>
				<output name="output" required="true">
					<description>Reference to output file</description>
					<extension>pdf</extension>
				</output>
			</outputs>
		</operation>
	</operations>
</tool>
