=== openplanets/scape-toolwrapper/toolwrapper-data/src/main/resources/tool-1.1_draft.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://scape-project.eu/tool" elementFormDefault="qualified"
	xmlns="http://scape-project.eu/tool" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">

	<xs:annotation>
		<xs:documentation>This schema ...</xs:documentation>
	</xs:annotation>

	<xs:element name="tool" type="Tool"/>

	<xs:complexType name="Tool">
		<xs:annotation>
			<xs:documentation>A command line tool.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="installation" type="Installation" minOccurs="0"/>
			<xs:element name="operations" type="Operations"/>
		</xs:sequence>
		<xs:attribute name="name" type="nonEmptyString" use="required"/>
		<xs:attribute name="version" type="nonEmptyString" use="required"/>
		<xs:attribute name="homepage" type="xs:anyURI"/>
		<xs:attribute name="schemaVersion" type="xs:decimal" use="required"/>
	</xs:complexType>


	<xs:complexType name="Installation">
		<xs:annotation>
			<xs:documentation>Declares 1 or more installation dependencies and
				license.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="dependencies" type="OperatingSystemDependency" maxOccurs="unbounded"
				minOccurs="0"/>
			<xs:element name="license" type="License" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="License">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="LicenseNameVersion" use="required"/>
				<xs:attribute name="otherName" type="xs:string" use="optional"/>
				<xs:attribute name="type" type="LicenseType" use="optional"/>
				<xs:attribute name="otherType" type="xs:string" use="optional"/>
				<xs:attribute name="uri" type="xs:anyURI" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="LicenseNameVersion">
		<xs:restriction base="xs:string">
			<!-- licenses from http://opensource.org/licenses -->
			<xs:enumeration value="AFL-3.0"/>
			<xs:enumeration value="AGPL-3.0"/>
			<xs:enumeration value="APL-1.0"/>
			<xs:enumeration value="Apache-2.0"/>
			<xs:enumeration value="APSL-2.0"/>
			<xs:enumeration value="Artistic-2.0"/>
			<xs:enumeration value="AAL"/>
			<!--<xs:enumeration value="BSD-3-Clause"/>-->
			<!--<xs:enumeration value="BSD-2-Clause"/>-->
			<xs:enumeration value="BSL-1.0"/>
			<xs:enumeration value="CATOSL-1.1"/>
			<xs:enumeration value="CDDL-1.0"/>
			<xs:enumeration value="CPAL-1.0"/>
			<xs:enumeration value="CUA-OPL-1.0"/>
			<xs:enumeration value="EUDatagrid"/>
			<xs:enumeration value="EPL-1.0"/>
			<xs:enumeration value="ECL-2.0"/>
			<xs:enumeration value="EFL-2.0"/>
			<xs:enumeration value="Entessa"/>
			<xs:enumeration value="EUPL-1.1"/>
			<xs:enumeration value="Fair"/>
			<xs:enumeration value="Frameworx-1.0"/>
			<xs:enumeration value="AGPL-3.0"/>
			<xs:enumeration value="GPL-2.0"/>
			<xs:enumeration value="GPL-3.0"/>
			<xs:enumeration value="LGPL-2.1"/>
			<xs:enumeration value="LGPL-3.0"/>
			<xs:enumeration value="HPND"/>
			<xs:enumeration value="IPL-1.0"/>
			<xs:enumeration value="IPA"/>
			<xs:enumeration value="ISC"/>
			<xs:enumeration value="LPPL-1.3c"/>
			<xs:enumeration value="LPL-1.02"/>
			<xs:enumeration value="MirOS"/>
			<xs:enumeration value="MS-PL"/>
			<xs:enumeration value="MS-RL"/>
			<xs:enumeration value="MIT"/>
			<xs:enumeration value="Motosoto"/>
			<xs:enumeration value="MPL-2.0"/>
			<xs:enumeration value="Multics"/>
			<xs:enumeration value="NASA-1.3"/>
			<xs:enumeration value="NTP"/>
			<xs:enumeration value="Naumen"/>
			<xs:enumeration value="NGPL"/>
			<xs:enumeration value="Nokia"/>
			<xs:enumeration value="NPOSL-3.0"/>
			<xs:enumeration value="OCLC-2.0"/>
			<xs:enumeration value="OFL-1.1"/>
			<xs:enumeration value="OGTSL"/>
			<xs:enumeration value="OSL-3.0"/>
			<xs:enumeration value="PHP-3.0"/>
			<xs:enumeration value="PostgreSQL"/>
			<xs:enumeration value="Python-2.0"/>
			<xs:enumeration value="CNRI-Python"/>
			<xs:enumeration value="QPL-1.0"/>
			<xs:enumeration value="RPSL-1.0"/>
			<xs:enumeration value="RPL-1.5"/>
			<xs:enumeration value="RSCPL"/>
			<xs:enumeration value="SimPL-2.0"/>
			<xs:enumeration value="Sleepycat"/>
			<xs:enumeration value="SPL-1.0"/>
			<xs:enumeration value="Watcom-1.0"/>
			<xs:enumeration value="NCSA"/>
			<xs:enumeration value="VSL-1.0"/>
			<xs:enumeration value="W3C"/>
			<xs:enumeration value="WXwindows"/>
			<xs:enumeration value="Xnet"/>
			<xs:enumeration value="ZPL-2.0"/>
			<xs:enumeration value="Zlib"/>

			<xs:enumeration value="Other"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="LicenseType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FLOSS"/>
			<xs:enumeration value="CC"/>
			<xs:enumeration value="Other"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="Dependency">
		<xs:sequence>
			<xs:element name="license" type="License" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="version" type="xs:string" use="optional"/>
	</xs:complexType>

	<xs:complexType name="OperatingSystemDependency">
		<xs:annotation>
			<xs:documentation>Declares an operating system dependency.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<!--<xs:element name="packageManagerConfig" type="PackageManagerConfig" minOccurs="1"
				maxOccurs="unbounded"/>-->
			<xs:element name="packageManager" type="PackageManager" minOccurs="1"
				maxOccurs="unbounded"/>
			<xs:element name="dependency" type="Dependency" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="operatingSystemName" type="OperatingSystemName" use="required"/>
		<xs:attribute name="otherOperatingSystemName" type="xs:string"/>
		<xs:attribute name="operatingSystemVersion" type="xs:string"/>
	</xs:complexType>

	<xs:simpleType name="OperatingSystemName">
		<xs:annotation>
			<xs:documentation>The operating system name. Use "Other" together with
				@otherOperatingSystemName to specify a different operating
				system.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Debian"/>
			<xs:enumeration value="Ubuntu"/>
			<xs:enumeration value="Redhat"/>
			<xs:enumeration value="CentOS"/>
			<xs:enumeration value="Windows"/>
			<xs:enumeration value="MacOS"/>
			<xs:enumeration value="Other"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="PackageManager">
		<xs:sequence>
			<xs:element name="config" type="ExtensionComplexType"/>
			<xs:element name="source" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="type" type="PackageManagerType" use="required"/>
		<xs:attribute name="otherType" type="xs:string" use="optional"/>
	</xs:complexType>

	<!-- extensionComplexType -->
	<xs:complexType name="ExtensionComplexType" mixed="true">
		<xs:sequence>
			<xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="PackageManagerType">
		<xs:annotation>
			<xs:documentation>The type of package manager. Use "Other" together with @otherFormat to
				specify a different package manager.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Dpkg"/>
			<xs:enumeration value="RPM"/>
			<xs:enumeration value="Other"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="nonEmptyString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="InOut">
		<xs:sequence>
			<xs:element name="format" type="Format" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="InOutAttrs">
		<xs:complexContent>
			<xs:extension base="InOut">
				<xs:attribute name="name" type="xs:string" use="required"/>
				<xs:attribute name="required" type="xs:boolean"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Format" mixed="false">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="registryName" type="xs:string" use="required"/>
				<xs:attribute name="version" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="Inputs">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element name="stdin" type="Stdin" maxOccurs="1" minOccurs="0"/>
			<xs:element name="input" type="Input" maxOccurs="unbounded" minOccurs="0"/>
			<xs:element name="parameter" type="Parameter" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Input">
		<xs:complexContent>
			<xs:extension base="InOutAttrs">
				<xs:sequence>
					<xs:element name="defaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Parameter">
		<xs:complexContent>
			<xs:extension base="InOutAttrs">
				<xs:sequence>
					<xs:element name="defaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Stdin">
		<xs:complexContent>
			<xs:extension base="InOut">
				<xs:attribute name="required" type="xs:boolean"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Outputs">
		<xs:sequence>
			<xs:element name="stdout" type="Stdout" maxOccurs="1" minOccurs="0"/>
			<xs:element name="output" type="Output" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Output">
		<xs:complexContent>
			<xs:extension base="InOutAttrs">
				<xs:sequence>
					<xs:element name="extension" type="xs:string" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Stdout">
		<xs:complexContent>
			<xs:extension base="InOut"> </xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Operations">
		<xs:annotation>
			<xs:documentation>Declares 1 or more operations provided by the tool.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="operation" type="Operation" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Operation">
		<xs:sequence>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="command" type="xs:string"/>
			<xs:element name="inputs" type="Inputs"/>
			<xs:element name="outputs" type="Outputs"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>

</xs:schema>

=== openplanets/scape-toolwrapper/developmentExamples/digital-preservation-migration-image-imagemagick-image2tiff.xml
<?xml version="1.0" encoding="utf-8" ?>
<tool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://scape-project.eu/tool toolwrapper-data/src/main/resources/tool-1.1_draft.xsd"
	xmlns="http://scape-project.eu/tool" xmlns:xlink="http://www.w3.org/1999/xlink"
	schemaVersion="1.1" name="ImageMagick" version="2.0.0"
	homepage="http://www.imagemagick.org/script/convert.php">
	<installation>
		<operatingSystem operatingSystemName="Debian">
			<packageManager type="Maven">
				<config>
						&lt;dependency&gt;
							&lt;groupId&gt;pt.gov.dgarq.roda&lt;/groupId&gt;     
							&lt;artifactId&gt;roda-common-utils&lt;/artifactId&gt;
							&lt;version&gt;1.0.0&lt;/version&gt;                 
						&lt;/dependency&gt;
						&lt;dependency&gt;
							&lt;groupId&gt;pt.gov.dgarq.roda&lt;/groupId&gt;     
							&lt;artifactId&gt;roda-common-data&lt;/artifactId&gt;
							&lt;version&gt;1.0.0&lt;/version&gt;                 
						&lt;/dependency&gt;
				</config>
				<source>http://artifactory.keep.pt/keep</source>
			</packageManager>
			<packageManager type="Dpkg">
				<config>imagemagick</config>
				<source>deb http://scape.keep.pt/apt stable main</source>
			</packageManager>
			<dependency name="imagemagick">
				<license name="Apache-2.0" type="FLOSS"
					uri="http://opensource.org/licenses/Apache-2.0" />
			</dependency>
		</operatingSystem>
		<operatingSystem operatingSystemName="Ubuntu">
			<packageManager type="Dpkg">
				<config>imagemagick</config>
				<source>deb http://scape.keep.pt/apt stable main</source>
			</packageManager>
			<dependency name="imagemagick">
				<license name="Apache-2.0" type="FLOSS"
					uri="http://opensource.org/licenses/Apache-2.0" />
			</dependency>
		</operatingSystem>
		<license name="Apache-2.0" type="FLOSS"
			uri="http://opensource.org/licenses/Apache-2.0" />
	</installation>

	<operations>
		<operation
			name="digital-preservation-migration-image-imagemagick-image2tiff">
			<description>Converts any ImageMagick supported image format to TIFF</description>
			<command>/usr/bin/convert ${params} ${input} tiff:${output}</command>
			<inputs>
				<input name="input" required="true">
					<description>Reference to input file</description>
				</input>
				<parameter name="params" required="false">
					<description>Additional input conversion parameters</description>
					<possibleValue description="no compression">-compress None</possibleValue>
					<possibleValue description="run length encoding">-compress RLE</possibleValue>
				</parameter>
			</inputs>
			<outputs>
				<output name="output" required="true">
					<description>Reference to output file</description>
					<extension>tiff</extension>
				</output>
			</outputs>
		</operation>
	</operations>
</tool>

=== openplanets/scape-toolwrapper/README_FILES/digital-preservation-migration-image-imagemagick-image2txt.xml
<?xml version="1.0" encoding="utf-8"?>
<tool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://scape-project.eu/tool" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://scape-project.eu/tool toolwrapper-data/src/main/resources/tool-1.1_draft.xsd" schemaVersion="1.1" name="ImageMagick" version="2.0.0" homepage="http://www.imagemagick.org/script/convert.php">
	<license name="Apache-2.0" type="FLOSS" uri="http://opensource.org/licenses/Apache-2.0"/>
	<installation>
		<operatingSystem operatingSystemName="Debian">
			<packageManager type="Dpkg">
				<config>imagemagick</config>
				<source>deb http://scape.keep.pt/apt stable main</source>
			</packageManager>
			<dependency name="imagemagick">
				<license name="Apache-2.0" type="FLOSS" uri="http://opensource.org/licenses/Apache-2.0"/>
			</dependency>
		</operatingSystem>
		<operatingSystem operatingSystemName="Ubuntu">
			<packageManager type="Dpkg">
				<config>imagemagick</config>
				<source>deb http://scape.keep.pt/apt stable main</source>
			</packageManager>
			<dependency name="imagemagick">
				<license name="Apache-2.0" type="FLOSS" uri="http://opensource.org/licenses/Apache-2.0"/>
			</dependency>
		</operatingSystem>
	</installation>
	<operations>
		<operation name="digital-preservation-migration-image-imagemagick-image2txt">
			<description>Converts any ImageMagick supported image format to Text</description>
			<command>/usr/bin/convert ${input} txt:${output}</command>
			<inputs>
				<input name="input" required="true">
					<description>Reference to input file</description>
				</input>
				<parameter name="params" required="false">
					<description>Additional conversion parameters</description>
				</parameter>
			</inputs>
			<outputs>
				<output name="output" required="true">
					<description>Reference to output file</description>
					<extension>txt</extension>
				</output>
			</outputs>
		</operation>
	</operations>
</tool>

=== openplanets/scape-toolwrapper/developmentExamples/digital-preservation-qaobject-imagemagick-compare-with-mse.xml
<?xml version="1.0" encoding="utf-8" ?>
<tool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://scape-project.eu/tool toolwrapper-data/src/main/resources/tool-1.1_draft.xsd"
	xmlns="http://scape-project.eu/tool" xmlns:xlink="http://www.w3.org/1999/xlink"
	schemaVersion="1.1" name="ImageMagick" version="2.0.0"
	homepage="http://www.imagemagick.org/script/compare.php">
	<installation>
		<operatingSystem operatingSystemName="Debian">
			<packageManager type="Maven">
				<config>
						&lt;dependency&gt;
							&lt;groupId&gt;pt.gov.dgarq.roda&lt;/groupId&gt;     
							&lt;artifactId&gt;roda-common-utils&lt;/artifactId&gt;
							&lt;version&gt;1.0.0&lt;/version&gt;                 
						&lt;/dependency&gt;
						&lt;dependency&gt;
							&lt;groupId&gt;pt.gov.dgarq.roda&lt;/groupId&gt;     
							&lt;artifactId&gt;roda-common-data&lt;/artifactId&gt;
							&lt;version&gt;1.0.0&lt;/version&gt;                 
						&lt;/dependency&gt;
				</config>
				<source>http://artifactory.keep.pt/keep</source>
			</packageManager>
			<packageManager type="Dpkg">
				<config>imagemagick</config>
				<source>deb http://scape.keep.pt/apt stable main</source>
			</packageManager>
			<dependency name="imagemagick">
				<license name="Apache-2.0" type="FLOSS"
					uri="http://opensource.org/licenses/Apache-2.0" />
			</dependency>
		</operatingSystem>
		<operatingSystem operatingSystemName="Ubuntu">
			<packageManager type="Dpkg">
				<config>imagemagick</config>
				<source>deb http://scape.keep.pt/apt stable main</source>
			</packageManager>
			<dependency name="imagemagick">
				<license name="Apache-2.0" type="FLOSS"
					uri="http://opensource.org/licenses/Apache-2.0" />
			</dependency>
		</operatingSystem>
		<license name="Apache-2.0" type="FLOSS"
			uri="http://opensource.org/licenses/Apache-2.0" />
	</installation>

	<operations>
		<operation
			name="digital-preservation-qaobject-imagemagick-compare-with-mse">
			<description>Compares 2 images using MSE method</description>
			<command>/usr/bin/compare -metric MSE ${input1} ${input2} ${difference}</command>
			<inputs>
				<input name="input1" required="true">
					<description>Reference to the first image file</description>
				</input>
				<input name="input2" required="true">
					<description>Reference to the second image file</description>
				</input>
				<parameter name="difference" required="true">
					<description>Image that will contain the difference between the two images</description>
				</parameter>
			</inputs>
			<outputs>
				<stdout />
			</outputs>
		</operation>
	</operations>
</tool>

=== openplanets/scape-toolwrapper/developmentExamples/digital-preservation-characterisation-video-ffprobe-video2xml.xml
<?xml version="1.0" encoding="utf-8" ?>
<tool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://scape-project.eu/tool toolwrapper-data/src/main/resources/tool-1.1_draft.xsd"
	xmlns="http://scape-project.eu/tool" xmlns:xlink="http://www.w3.org/1999/xlink"
	schemaVersion="1.1" name="FFmpeg" version="1.0.1" homepage="http://ffmpeg.org/">
	
	<installation>
		<dependencies operatingSystemName="Debian">
			<packageManager type="Dpkg">
				<config>ffmpeg (>= 0.10.0)</config>
				<source>deb http://ppa.launchpad.net/jon-severinsson/ffmpeg/ubuntu precise main 
deb-src http://ppa.launchpad.net/jon-severinsson/ffmpeg/ubuntu precise main </source>
			</packageManager>
			<dependency name="ffmpeg" version=">= 0.10.0">
				<license name="LGPL-2.1" uri="http://opensource.org/licenses/LGPL-2.1" type="FLOSS"></license>
			</dependency>
		</dependencies>
		<license name="LGPL-2.1" uri="http://opensource.org/licenses/LGPL-2.1" type="FLOSS" />
	</installation>

	<operations>
		<operation
			name="digital-preservation-characterisation-video-ffprobe-video2xml">
			<description>Characterises video and outputs information as XML</description>
			<command>ffprobe -show_streams -show_format -print_format xml="x=1" -noprivate -show_versions -i ${input} > ${output}</command>
			<inputs>
				<input name="input" required="true">
					<description>Reference to input file</description>
				</input>
				<parameter name="params" required="false">
					<description>Additional conversion parameters</description>
				</parameter>
			</inputs>
			<outputs>
				<output name="output" required="true">
					<format registryName="web">http://www.ffmpeg.org/schema/ffprobe.xsd</format>
					<description>Reference to output file</description>
					<extension>xml</extension>
				</output>
			</outputs>
		</operation>
	</operations>
</tool>
